### ISSUE TITLE
"McMenu trial version"

### ISSUE THREAD

**Issue by DealsBeam** [sugar3-io/gelati-sugarfree#1]
Thanks for the template, when I use it on my blogspot it shows "McMenu trial version" at the top of the page, also could you please release a liquid version? I'd like to use a liquid version over a grid version where it would show the entire post without needing to click "Read more"

**Comment by christiansam** [comment]
> This blog template employs third-party components from Menucool.com which provide versatile Menu and Gallery elements to enhance the blog template's UX in a significant way.

> While there exists no association, Gelati Sugarfree was provided with free licenses for its integrated Menucool.com components, valid for all blog template instances running on standard Blogger *.blogspot.com subdomains. Users that plan to utilize this blog template with custom domain configured Blogger blog-instances have to provide domain-bound licenses, purchasable form Menucool...

- If you use Blogger's default "&lt;your-blog-name&gt;.blogspot.com" domain for your blog, Menucool.com's provided license and resources, as available in Gelati Sugarfree Template should work out-of-the-box: https://gelati.sugar3.io/p/docs.html#quick_installation

```
<head>
  ...
  <script type="text/javascript">
        var blogTemplate = {};
        blogTemplate.licenseKeys = JSON.parse('{"licenseKeys": { "menu": "2c6b88", "slider": "b2l868", "tooltip": "248t8" }}').licenseKeys;
        blogTemplate.resourcesUrl = '//gelatistatic.sugar3.io';
        blogTemplate.resourcesVersion = 'v1';
      </script>
  ...
  <link href="//gelatistatic.sugar3.io/v1/css/main.css" rel="stylesheet" type="text/css">
  <script src="//gelatistatic.sugar3.io/v1/js/app.js" type="text/javascript"></script>
```

- If you 've configured your Blogger blog to use a custom domain please have a look at the section named **Custom Domain Usage** on https://gelati.sugar3.io/p/docs.html#advanced_setup, on how to acquire and insert your individual, domain-bound license.

_Hint:_ Gelati Sugarfree Resources "app.js" and "main.css" include bundled (slightly adapted) versions of [Menucool's](http://www.menucool.com) _McMenu_, _Ninja Slider_ and _JS Tooltip_.

- Regarding your feature request of an alternative blogpost presentation on [Index](https://bloggercode-blogconnexion.blogspot.com/1978/11/data-blog-pageType.html) **blog.pageType**:

Currently I have no plans to implement such a feature. 

If you plan to host Gelati Sugarfree Resources on your own infrastructure and/or want to extend Gelati Sugarfree Template in general please have a look at the section named **Further Customization and Development** on https://gelati.sugar3.io/p/docs.html#advanced_setup
